export const GET_GAMES = "GET_GAMES";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const SEARCH_BY_ID = "SEARCH_BY_ID";
export const GET_PLATFORMS = "GET_PLATFORMS";
export const GET_GENRES = "GET_GENRES";
export const POST_VIDEOGAME = "POST_VIDEOGAME";
export const CLEAR_GAME_DETAIL = "CLEAR_GAME_DETAIL";
export const ORDER_ASC = "ORDER_ASC"; //nombre y rating
export const ORDER_DESC = "ORDER_DESC";
export const ORDER_MORE_RATING = "ORDER_MORE_RATING,";
export const ORDER_LESS_RATING = "ORDER_LESS_RATING,";
export const FILTER_ORIGIN = "FILTER_ORIGIN";
export const FILTER_GENRES = "FILTER_GENRES";
export const SHOW_GAMES = "SHOW_GAMES";
